#!/bin/bash
#
#SBATCH --job-name=BRO_BIDS
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 2:00:00
#SBATCH --mem-per-cpu 80000
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID
#SBATCH -o /projects/niblab/bids_projects/Experiments/BRO/BIDS/code/error_files/bids_%a_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/BRO/BIDS/code/error_files/bids_%a_err.txt

if [ ${SLURM_ARRAY_TASK_ID} -lt 10 ]; then
    id="00${SLURM_ARRAY_TASK_ID}"
else
    id="0${SLURM_ARRAY_TASK_ID}"
fi


singularity exec -B /:/base_dir /projects/niblab/bids_projects/Singularity_Containers/heudiconv_05_2019.simg \
heudiconv -b -d /base_dir/projects/niblab/bids_projects/Experiments/BRO/DICOM/ses-{session}/sub-{subject}/*dcm -s $id -ss 1 \
-f /base_dir/projects/niblab/bids_projects/Experiments/BRO/BIDS/code/BRO_heuristic.py \
-c dcm2niix -o /base_dir/projects/niblab/bids_projects/Experiments/BRO/BIDS
